// The following code is used to verify a proof generated by the game server's
// Elliptic Curve Verifiable Random Function (ECVRF).
const { verify } = require('@roamin/ecvrf')
const hex = require('string-hex')

// Replace with verification details from the game you're validating:
const pk = '031dbd46219fac7d8f98b601eb3bc337570e1477ec7e0a6d2da318b09acbcf1ca9'
const α = '{"nonce":"0240xXHnHuro","vendor":"sbx","game":"plinko","entropy":"client-supplied-stuff"}'
const π = '02d2184a381e694fc73a8695293cf2b125e4aaba68521fa1b8826d3f337311efdab20afbb31ee462ce354bbbf7119b9c73345769b0feebda0a95213b1bafa10a54c55b84b5859ec71a21fc8b332972cd6c'
const β = 'e3a4f253701f33dbc507ff7d6f878927e41ce142cc93738d6c9d38b9a5a26b6b'

let res = false
try {
    res = verify(pk, π, hex(α))
} catch (e) {}

console.log('Verification result:', res === β ? '✅ Verified' : '❌ Failed')
